// This file was generated by prisma-field-encryption.

import type { PrismaClient } from '../C:\Users\razwiz\Documents\prac\portfolio-builds\pocket-pal\node_modules\.pnpm\@prisma+client@4.13.0_prisma@4.14.0\node_modules\@prisma\client'
import { migrate as migrateincome } from './income'
import { migrate as migrateexpenses } from './expenses'
import { migrate as migrateinvestments } from './investments'

export interface ProgressReport {
  model: string
  processed: number
  totalCount: number
  performance: number
}

export type ProgressReportCallback = (
  progress: ProgressReport
) => void | Promise<void>

export const defaultProgressReport: ProgressReportCallback = ({
  model,
  totalCount,
  processed,
  performance
}) => {
  const length = totalCount.toString().length
  const pct = Math.round((100 * processed) / totalCount)
    .toString()
    .padStart(3)
  console.info(
    `${model.padEnd(11)} ${pct}% processed ${processed
      .toString()
      .padStart(length)} / ${totalCount} (took ${performance.toFixed(2)}ms)`
  )
}

// --

export type MigrationReport = {
  income: number,
  expenses: number,
  investments: number
}

/**
 * Migrate models concurrently.
 *
 * Processed models:
 * - income
 * - expenses
 * - investments
 *
 * @returns a dictionary of the number of processed records per model.
 */
export async function migrate(
  client: PrismaClient,
  reportProgress: ProgressReportCallback = defaultProgressReport
): Promise<MigrationReport> {
  const [
    processedincome,
    processedexpenses,
    processedinvestments
  ] = await Promise.all([
    migrateincome(client, reportProgress),
    migrateexpenses(client, reportProgress),
    migrateinvestments(client, reportProgress)
  ])
  return {
    income: processedincome,
    expenses: processedexpenses,
    investments: processedinvestments
  }
}
